<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Privacy Policy - Null Fake</title>
  <meta name="description" content="Privacy Policy for Null Fake - Amazon Review Analysis Tool" />
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  @vite(['resources/css/app.css'])
</head>
<body class="bg-gray-100 text-gray-800">

<div class="min-h-screen bg-gray-100">
  @include('partials.header')

  <!-- Main Content -->
  <main class="max-w-4xl mx-auto px-6 py-8">
    <div class="bg-white rounded-lg shadow-sm p-8">
      <h1 class="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
      
      <p class="text-gray-600 mb-6">Last updated: June 2025</p>

      <div class="prose prose-gray max-w-none">
        
        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Information We Collect</h2>
        <p class="mb-4">When you use Null Fake, we collect the following information:</p>
        <ul class="list-disc pl-6 mb-6">
          <li><strong>Product URLs:</strong> Amazon product URLs you submit for analysis</li>
          <li><strong>Analysis Results:</strong> Review data and authenticity scores generated by our AI analysis</li>
          <li><strong>Usage Data:</strong> Basic analytics about how our service is used (no personal identification)</li>
          <li><strong>IP Address:</strong> For security and abuse prevention through captcha verification</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">How We Use Your Information</h2>
        <p class="mb-4">We use the collected information to:</p>
        <ul class="list-disc pl-6 mb-6">
          <li>Provide Amazon review authenticity analysis</li>
          <li>Cache results for faster future lookups (30 days)</li>
          <li>Prevent abuse and spam through captcha verification</li>
          <li>Improve our AI analysis algorithms</li>
          <li>Monitor service performance and reliability</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Data Storage and Retention</h2>
        <p class="mb-6">
          Analysis results are stored in our database for 30 days to provide instant results for repeat requests. 
          After 30 days, cached analysis data may be refreshed with new data. We do not store personal 
          information that could identify individual users.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Third-Party Services</h2>
        <p class="mb-4">Null Fake uses the following third-party services:</p>
        <ul class="list-disc pl-6 mb-6">
          <li><strong>OpenAI:</strong> For AI-powered review analysis (subject to OpenAI's privacy policy)</li>
          <li><strong>Unwrangle API:</strong> For fetching Amazon review data (subject to their privacy policy)</li>
          <li><strong>Captcha Services:</strong> reCAPTCHA or hCaptcha for spam prevention</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Data Sharing</h2>
        <p class="mb-6">
          We do not sell, trade, or share your data with third parties except as necessary to provide 
          our service (e.g., sending review data to OpenAI for analysis). All data sharing is done 
          in accordance with the privacy policies of our service providers.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Security</h2>
        <p class="mb-6">
          We implement appropriate security measures to protect your data. However, no internet 
          transmission is 100% secure. We cannot guarantee absolute security of data transmitted 
          to our service.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Your Rights</h2>
        <p class="mb-4">You have the right to:</p>
        <ul class="list-disc pl-6 mb-6">
          <li>Request information about data we have collected</li>
          <li>Request deletion of your analysis data</li>
          <li>Contact us with privacy concerns</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Open Source</h2>
        <p class="mb-6">
          Null Fake is open source software released under the MIT License. You can review our 
          code and data handling practices on 
          <a href="https://github.com/stardothosting/nullfake" class="text-brand hover:underline">GitHub</a>.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Changes to This Policy</h2>
        <p class="mb-6">
          We may update this privacy policy from time to time. Any changes will be posted on this page 
          with an updated "Last updated" date.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Contact Us</h2>
        <p class="mb-6">
          If you have questions about this privacy policy, please contact us through our 
          <a href="https://github.com/stardothosting/nullfake" class="text-brand hover:underline">GitHub repository</a>.
        </p>

      </div>
    </div>
  </main>

  <!-- Footer -->
  <footer class="text-center text-gray-500 text-sm mt-10 p-2">
    <div class="flex items-center justify-center mb-2">
      <span class="flex items-center">
        built with
        <span class="inline-block align-middle text-red-500 mx-1" aria-label="love" title="love">
          <svg xmlns="http://www.w3.org/2000/svg" class="inline align-middle h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
            <path d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"/>
          </svg>
        </span>
        by&nbsp;<a href="https://shift8web.ca" class="text-indigo-600 hover:underline" target="_blank" rel="noopener">shift8 web</a>
      </span>
      <span class="mx-2">•</span>
      <a href="{{ route('products.index') }}" class="text-gray-600 hover:text-gray-800 flex items-center" title="Browse all analyzed products">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/>
        </svg>
        All analyzed products
      </a>
      <span class="mx-2">•</span>
      <a href="https://github.com/stardothosting/nullfake" class="text-gray-600 hover:text-gray-800 flex items-center" target="_blank" rel="noopener" title="View source on GitHub">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.30.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
        </svg>
        GitHub
      </a>
    </div>
    <div class="flex items-center justify-center space-x-4 text-xs">
      <a href="https://github.com/stardothosting/nullfake/blob/main/LICENSE" class="text-gray-500 hover:text-gray-700" target="_blank" rel="noopener">MIT License</a>
      <span>•</span>
      <a href="/privacy" class="text-gray-500 hover:text-gray-700">Privacy Policy</a>
      <span>•</span>
      <a href="/contact" class="text-gray-500 hover:text-gray-700">Contact</a>
    </div>
  </footer>

</div>

</body>
</html> 