<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Privacy Policy - Null Fake</title>
  <meta name="description" content="Privacy Policy for Null Fake - Amazon Review Analysis Tool" />
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 text-gray-800">

<div class="min-h-screen bg-gray-100">
  <!-- Header -->
  <header class="bg-white shadow-sm border-b">
    <div class="max-w-4xl mx-auto px-6 py-4">
      <div class="flex items-center">
        <a href="/" class="flex items-center space-x-3">
          <div class="w-8 h-8 bg-teal-600 rounded-lg flex items-center justify-center">
            <svg class="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
          </div>
          <span class="text-xl font-bold text-gray-900">NULL FAKE</span>
        </a>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <main class="max-w-4xl mx-auto px-6 py-8">
    <div class="bg-white rounded-lg shadow-sm p-8">
      <h1 class="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
      
      <p class="text-gray-600 mb-6">Last updated: June 2025</p>

      <div class="prose prose-gray max-w-none">
        
        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Information We Collect</h2>
        <p class="mb-4">When you use Null Fake, we collect the following information:</p>
        <ul class="list-disc pl-6 mb-6">
          <li><strong>Product URLs:</strong> Amazon product URLs you submit for analysis</li>
          <li><strong>Analysis Results:</strong> Review data and authenticity scores generated by our AI analysis</li>
          <li><strong>Usage Data:</strong> Basic analytics about how our service is used (no personal identification)</li>
          <li><strong>IP Address:</strong> For security and abuse prevention through captcha verification</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">How We Use Your Information</h2>
        <p class="mb-4">We use the collected information to:</p>
        <ul class="list-disc pl-6 mb-6">
          <li>Provide Amazon review authenticity analysis</li>
          <li>Cache results for faster future lookups (30 days)</li>
          <li>Prevent abuse and spam through captcha verification</li>
          <li>Improve our AI analysis algorithms</li>
          <li>Monitor service performance and reliability</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Data Storage and Retention</h2>
        <p class="mb-6">
          Analysis results are stored in our database for 30 days to provide instant results for repeat requests. 
          After 30 days, cached analysis data may be refreshed with new data. We do not store personal 
          information that could identify individual users.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Third-Party Services</h2>
        <p class="mb-4">Null Fake uses the following third-party services:</p>
        <ul class="list-disc pl-6 mb-6">
          <li><strong>OpenAI:</strong> For AI-powered review analysis (subject to OpenAI's privacy policy)</li>
          <li><strong>Unwrangle API:</strong> For fetching Amazon review data (subject to their privacy policy)</li>
          <li><strong>Captcha Services:</strong> reCAPTCHA or hCaptcha for spam prevention</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Data Sharing</h2>
        <p class="mb-6">
          We do not sell, trade, or share your data with third parties except as necessary to provide 
          our service (e.g., sending review data to OpenAI for analysis). All data sharing is done 
          in accordance with the privacy policies of our service providers.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Security</h2>
        <p class="mb-6">
          We implement appropriate security measures to protect your data. However, no internet 
          transmission is 100% secure. We cannot guarantee absolute security of data transmitted 
          to our service.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Your Rights</h2>
        <p class="mb-4">You have the right to:</p>
        <ul class="list-disc pl-6 mb-6">
          <li>Request information about data we have collected</li>
          <li>Request deletion of your analysis data</li>
          <li>Contact us with privacy concerns</li>
        </ul>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Open Source</h2>
        <p class="mb-6">
          Null Fake is open source software released under the MIT License. You can review our 
          code and data handling practices on 
          <a href="https://github.com/stardothosting/nullfake" class="text-blue-600 hover:underline">GitHub</a>.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Changes to This Policy</h2>
        <p class="mb-6">
          We may update this privacy policy from time to time. Any changes will be posted on this page 
          with an updated "Last updated" date.
        </p>

        <h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4">Contact Us</h2>
        <p class="mb-6">
          If you have questions about this privacy policy, please contact us through our 
          <a href="https://github.com/stardothosting/nullfake" class="text-blue-600 hover:underline">GitHub repository</a>.
        </p>

      </div>
    </div>
  </main>

  <!-- Footer -->
  <footer class="text-center text-gray-500 text-sm mt-10 p-2">
    <div class="flex items-center justify-center mb-2">
      <a href="/" class="text-teal-600 hover:underline">← Back to Null Fake</a>
    </div>
    <div class="flex items-center justify-center space-x-4 text-xs">
      <a href="https://github.com/stardothosting/nullfake/blob/main/LICENSE" class="text-gray-500 hover:text-gray-700" target="_blank" rel="noopener">MIT License</a>
      <span>•</span>
      <span class="text-gray-400">Privacy Policy</span>
    </div>
  </footer>

</div>

</body>
</html> 